/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author JAMILIA
 */
public class CadastroPlanos extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroPlanos
     */
    public CadastroPlanos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDescricaoPlano = new javax.swing.JLabel();
        campoValorPlano = new javax.swing.JTextField();
        labelValorPlano = new javax.swing.JLabel();
        campoCondicoesPlano = new javax.swing.JTextField();
        labelCondicoesPlano = new javax.swing.JLabel();
        botaoCadastrar = new javax.swing.JButton();
        labelNomePlano = new javax.swing.JLabel();
        campoNomePlano = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDescricaoPlano = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Planos");

        labelDescricaoPlano.setText("Descrição do Plano:");

        campoValorPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoValorPlanoActionPerformed(evt);
            }
        });

        labelValorPlano.setText("Valor do Plano:");

        campoCondicoesPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCondicoesPlanoActionPerformed(evt);
            }
        });

        labelCondicoesPlano.setText("Condicoes do Plano:");

        botaoCadastrar.setText("Cadastrar");

        labelNomePlano.setText("Nome Plano:");

        campoNomePlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomePlanoActionPerformed(evt);
            }
        });

        textAreaDescricaoPlano.setColumns(20);
        textAreaDescricaoPlano.setRows(5);
        jScrollPane1.setViewportView(textAreaDescricaoPlano);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescricaoPlano, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelValorPlano, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNomePlano, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCondicoesPlano, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoCondicoesPlano)
                    .addComponent(campoValorPlano)
                    .addComponent(campoNomePlano))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomePlano)
                    .addComponent(campoNomePlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValorPlano)
                    .addComponent(campoValorPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCondicoesPlano)
                    .addComponent(campoCondicoesPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDescricaoPlano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCadastrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoValorPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoValorPlanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoValorPlanoActionPerformed

    private void campoCondicoesPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCondicoesPlanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCondicoesPlanoActionPerformed

    private void campoNomePlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomePlanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomePlanoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JTextField campoCondicoesPlano;
    private javax.swing.JTextField campoNomePlano;
    private javax.swing.JTextField campoValorPlano;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCondicoesPlano;
    private javax.swing.JLabel labelDescricaoPlano;
    private javax.swing.JLabel labelNomePlano;
    private javax.swing.JLabel labelValorPlano;
    private javax.swing.JTextArea textAreaDescricaoPlano;
    // End of variables declaration//GEN-END:variables
}
