/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Desktop;
import javax.swing.plaf.DesktopIconUI;
import javax.swing.plaf.DesktopPaneUI;

/**
 *
 * @author JAMILIA
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        labelColaborador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        menuItemAcademia = new javax.swing.JMenuItem();
        menuItemAlunos = new javax.swing.JMenuItem();
        menuItemAvaliacoes = new javax.swing.JMenuItem();
        menuItemContratos = new javax.swing.JMenuItem();
        menuItemFuncionarios = new javax.swing.JMenuItem();
        menuItemPlanos = new javax.swing.JMenuItem();
        menuPesquisas = new javax.swing.JMenu();
        jMenuPesquisaAcademia = new javax.swing.JMenuItem();
        jMenuPesquisaAlunos = new javax.swing.JMenuItem();
        jMenuPesquisaAvaliacoes = new javax.swing.JMenuItem();
        jMenuPesquisaContratos = new javax.swing.JMenuItem();
        jMenuPesquisaFuncionarios = new javax.swing.JMenuItem();
        jMenuPesquisaPlanos = new javax.swing.JMenuItem();
        menuManutencao = new javax.swing.JMenu();
        menuItemBackupBancoDados = new javax.swing.JMenuItem();
        menuItemRestaurarBancoDados = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuItemRelatorioAluno = new javax.swing.JMenuItem();
        menuItemRelatorioFuncionario = new javax.swing.JMenuItem();
        menuItemRelatorioPlanos = new javax.swing.JMenuItem();
        menuItemRelatoriosContratos = new javax.swing.JMenuItem();
        menuPagamentos = new javax.swing.JMenu();
        menuItemPagamentosPagos = new javax.swing.JMenuItem();
        menuItemPagamentosAtrasados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dp.setName("dp"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        labelColaborador.setText("Colaborador:");

        jLabel2.setName("LabelNomeColaborador"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelColaborador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(821, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelColaborador)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dp.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpLayout = new javax.swing.GroupLayout(dp);
        dp.setLayout(dpLayout);
        dpLayout.setHorizontalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dpLayout.setVerticalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpLayout.createSequentialGroup()
                .addGap(0, 529, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBarPrincipal.setBackground(new java.awt.Color(0, 102, 255));
        jMenuBarPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        menuCadastros.setText("Cadastros");

        menuItemAcademia.setText("Academia");
        menuItemAcademia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAcademiaActionPerformed(evt);
            }
        });
        menuCadastros.add(menuItemAcademia);

        menuItemAlunos.setText("Alunos");
        menuItemAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAlunosActionPerformed(evt);
            }
        });
        menuCadastros.add(menuItemAlunos);

        menuItemAvaliacoes.setText("Avaliacoes");
        menuItemAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAvaliacoesActionPerformed(evt);
            }
        });
        menuCadastros.add(menuItemAvaliacoes);

        menuItemContratos.setText("Contratos");
        menuItemContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemContratosActionPerformed(evt);
            }
        });
        menuCadastros.add(menuItemContratos);

        menuItemFuncionarios.setText("Funcionarios");
        menuItemFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFuncionariosActionPerformed(evt);
            }
        });
        menuCadastros.add(menuItemFuncionarios);

        menuItemPlanos.setText("Planos");
        menuItemPlanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPlanosActionPerformed(evt);
            }
        });
        menuCadastros.add(menuItemPlanos);

        jMenuBarPrincipal.add(menuCadastros);

        menuPesquisas.setText("Pesquisas");

        jMenuPesquisaAcademia.setText("Academia");
        jMenuPesquisaAcademia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPesquisaAcademiaActionPerformed(evt);
            }
        });
        menuPesquisas.add(jMenuPesquisaAcademia);

        jMenuPesquisaAlunos.setText("Alunos");
        jMenuPesquisaAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPesquisaAlunosActionPerformed(evt);
            }
        });
        menuPesquisas.add(jMenuPesquisaAlunos);

        jMenuPesquisaAvaliacoes.setText("Avaliacoes");
        jMenuPesquisaAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPesquisaAvaliacoesActionPerformed(evt);
            }
        });
        menuPesquisas.add(jMenuPesquisaAvaliacoes);

        jMenuPesquisaContratos.setText("Contratos");
        jMenuPesquisaContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPesquisaContratosActionPerformed(evt);
            }
        });
        menuPesquisas.add(jMenuPesquisaContratos);

        jMenuPesquisaFuncionarios.setText("Funcionarios");
        jMenuPesquisaFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPesquisaFuncionariosActionPerformed(evt);
            }
        });
        menuPesquisas.add(jMenuPesquisaFuncionarios);

        jMenuPesquisaPlanos.setText("Planos");
        jMenuPesquisaPlanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPesquisaPlanosActionPerformed(evt);
            }
        });
        menuPesquisas.add(jMenuPesquisaPlanos);

        jMenuBarPrincipal.add(menuPesquisas);

        menuManutencao.setText("Manutencao");

        menuItemBackupBancoDados.setText("Backup do banco de dados");
        menuItemBackupBancoDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBackupBancoDadosActionPerformed(evt);
            }
        });
        menuManutencao.add(menuItemBackupBancoDados);

        menuItemRestaurarBancoDados.setText("Restaurar banco de dados");
        menuItemRestaurarBancoDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRestaurarBancoDadosActionPerformed(evt);
            }
        });
        menuManutencao.add(menuItemRestaurarBancoDados);

        jMenuBarPrincipal.add(menuManutencao);

        menuRelatorios.setText("Relatórios");

        menuItemRelatorioAluno.setText("Alunos");
        menuItemRelatorioAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRelatorioAlunoActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuItemRelatorioAluno);

        menuItemRelatorioFuncionario.setText("Funcionarios");
        menuItemRelatorioFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRelatorioFuncionarioActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuItemRelatorioFuncionario);

        menuItemRelatorioPlanos.setText("Planos");
        menuItemRelatorioPlanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRelatorioPlanosActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuItemRelatorioPlanos);

        menuItemRelatoriosContratos.setText("Contratos");
        menuItemRelatoriosContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRelatoriosContratosActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuItemRelatoriosContratos);

        jMenuBarPrincipal.add(menuRelatorios);

        menuPagamentos.setText("Pagamentos");

        menuItemPagamentosPagos.setText("Pagos");
        menuPagamentos.add(menuItemPagamentosPagos);

        menuItemPagamentosAtrasados.setText("Atrasados");
        menuPagamentos.add(menuItemPagamentosAtrasados);

        jMenuBarPrincipal.add(menuPagamentos);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAcademiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAcademiaActionPerformed
        CadastroAcademia acad = new CadastroAcademia();
        getContentPane().add(acad);
        acad.setVisible(true);
        acad.show();
    }//GEN-LAST:event_menuItemAcademiaActionPerformed

    private void menuItemAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAlunosActionPerformed
        CadastroAlunos ca = new CadastroAlunos();
	getContentPane().add(ca);
        ca.setVisible(true);
        ca.show();
    }//GEN-LAST:event_menuItemAlunosActionPerformed

    private void menuItemFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFuncionariosActionPerformed
        CadastroFuncionarios cf = new CadastroFuncionarios();
        getContentPane().add(cf);
        cf.setVisible(true);
        cf.show();
    }//GEN-LAST:event_menuItemFuncionariosActionPerformed

    private void menuItemAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAvaliacoesActionPerformed
        CadastroAvaliacoes cav = new CadastroAvaliacoes();
        getContentPane().add(cav);
        cav.setVisible(true);
        cav.show();
    }//GEN-LAST:event_menuItemAvaliacoesActionPerformed

    private void menuItemContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemContratosActionPerformed
        CadastroContratos cc = new CadastroContratos();
        getContentPane().add(cc);
        cc.setVisible(true);
        cc.show();
    }//GEN-LAST:event_menuItemContratosActionPerformed

    private void menuItemPlanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPlanosActionPerformed
        CadastroPlanos cp = new CadastroPlanos();
        getContentPane().add(cp);
        cp.setVisible(true);
        cp.show();
    }//GEN-LAST:event_menuItemPlanosActionPerformed

    private void jMenuPesquisaAcademiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPesquisaAcademiaActionPerformed
        PesquisaAcademia pacad = new PesquisaAcademia();
        getContentPane().add(pacad);
        pacad.setVisible(true);
        pacad.show();
    }//GEN-LAST:event_jMenuPesquisaAcademiaActionPerformed

    private void jMenuPesquisaAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPesquisaAlunosActionPerformed
        PesquisaAluno palun = new PesquisaAluno();
        getContentPane().add(palun);
        palun.setVisible(true);
        palun.show();
    }//GEN-LAST:event_jMenuPesquisaAlunosActionPerformed

    private void jMenuPesquisaAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPesquisaAvaliacoesActionPerformed
        PesquisaAvaliacao paval = new PesquisaAvaliacao();
        getContentPane().add(paval);
        paval.setVisible(true);
        paval.show();
    }//GEN-LAST:event_jMenuPesquisaAvaliacoesActionPerformed

    private void jMenuPesquisaContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPesquisaContratosActionPerformed
        PesquisaContrato pcon = new PesquisaContrato();
        getContentPane().add(pcon);
        pcon.setVisible(true);
        pcon.show();
    }//GEN-LAST:event_jMenuPesquisaContratosActionPerformed

    private void jMenuPesquisaFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPesquisaFuncionariosActionPerformed
        PesquisarFuncionario pfunc = new PesquisarFuncionario();
        getContentPane().add(pfunc);
        pfunc.setVisible(true);
        pfunc.show();
    }//GEN-LAST:event_jMenuPesquisaFuncionariosActionPerformed

    private void jMenuPesquisaPlanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPesquisaPlanosActionPerformed
        PesquisarPlano pplan = new PesquisarPlano();
        getContentPane().add(pplan);
        pplan.setVisible(true);
        pplan.show();
    }//GEN-LAST:event_jMenuPesquisaPlanosActionPerformed

    private void menuItemBackupBancoDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBackupBancoDadosActionPerformed
        Backup back = new Backup();
        getContentPane().add(back);
        back.setVisible(true);
        back.show();
    }//GEN-LAST:event_menuItemBackupBancoDadosActionPerformed

    private void menuItemRestaurarBancoDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRestaurarBancoDadosActionPerformed
        RestaurarBackup rback = new RestaurarBackup();
        getContentPane().add(rback);
        rback.setVisible(true);
        rback.show();
    }//GEN-LAST:event_menuItemRestaurarBancoDadosActionPerformed

    private void menuItemRelatorioAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRelatorioAlunoActionPerformed
        RelatorioAlunos rel_alun = new RelatorioAlunos();
        getContentPane().add(rel_alun);
        rel_alun.setVisible(true);
        rel_alun.show();
    }//GEN-LAST:event_menuItemRelatorioAlunoActionPerformed

    private void menuItemRelatorioFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRelatorioFuncionarioActionPerformed
        RelatorioFuncionarios rel_func = new RelatorioFuncionarios();
        getContentPane().add(rel_func);
        rel_func.setVisible(true);
        rel_func.show();
    }//GEN-LAST:event_menuItemRelatorioFuncionarioActionPerformed

    private void menuItemRelatorioPlanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRelatorioPlanosActionPerformed
        RelatorioPlanos rel_plan = new RelatorioPlanos();
        getContentPane().add(rel_plan);
        rel_plan.setVisible(true);
        rel_plan.show();
    }//GEN-LAST:event_menuItemRelatorioPlanosActionPerformed

    private void menuItemRelatoriosContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRelatoriosContratosActionPerformed
        RelatorioContratos rel_cont = new RelatorioContratos();
        getContentPane().add(rel_cont);
        rel_cont.setVisible(true);
        rel_cont.show();
    }//GEN-LAST:event_menuItemRelatoriosContratosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenuItem jMenuPesquisaAcademia;
    private javax.swing.JMenuItem jMenuPesquisaAlunos;
    private javax.swing.JMenuItem jMenuPesquisaAvaliacoes;
    private javax.swing.JMenuItem jMenuPesquisaContratos;
    private javax.swing.JMenuItem jMenuPesquisaFuncionarios;
    private javax.swing.JMenuItem jMenuPesquisaPlanos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelColaborador;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenuItem menuItemAcademia;
    private javax.swing.JMenuItem menuItemAlunos;
    private javax.swing.JMenuItem menuItemAvaliacoes;
    private javax.swing.JMenuItem menuItemBackupBancoDados;
    private javax.swing.JMenuItem menuItemContratos;
    private javax.swing.JMenuItem menuItemFuncionarios;
    private javax.swing.JMenuItem menuItemPagamentosAtrasados;
    private javax.swing.JMenuItem menuItemPagamentosPagos;
    private javax.swing.JMenuItem menuItemPlanos;
    private javax.swing.JMenuItem menuItemRelatorioAluno;
    private javax.swing.JMenuItem menuItemRelatorioFuncionario;
    private javax.swing.JMenuItem menuItemRelatorioPlanos;
    private javax.swing.JMenuItem menuItemRelatoriosContratos;
    private javax.swing.JMenuItem menuItemRestaurarBancoDados;
    private javax.swing.JMenu menuManutencao;
    private javax.swing.JMenu menuPagamentos;
    private javax.swing.JMenu menuPesquisas;
    private javax.swing.JMenu menuRelatorios;
    // End of variables declaration//GEN-END:variables
}
